export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_PROFILE = 'GET_PROFILE';
export const POST_PROFILE = 'POST_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';